coralogix/coralogix-operator

.github/workflows/helm-chart-deploy.yml
I'm adding a command to change the charts dir before packing and pushing the artifact.
#13
=> [FIX] changing to chart dir

charts/coralogix-operator/Chart.yaml, charts/coralogix-operator/templates/NOTES.txt
I'm adding helm install validation for the required fields.
=> [CHORE] adding helm validation

.github/workflows/build.yml, .github/workflows/container.yaml, .github/workflows/docs.yml, .github/workflows/e2e-tests.yaml, .github/workflows/helm-chart-deploy.yml, .github/workflows/semantic-release.yml
I'm removing the `master` branch name from all Github workflows after changing the branch name from `master` to `main`.
=> [CHORE] Removing master name from workflows

charts/coralogix-operator/Chart.yaml, charts/coralogix-operator/README.md
I'm upgrading helm chart version and app version.
=> [CHORE] upgrading chart

.github/workflows/helm-update.yaml
I'm adding a new workflow to watch new tags and update the helm chart with new app version.
=> [CHORE] adding workflow to update helm on new tag

.github/workflows/helm-update.yaml
=> [FIX] push step

charts/coralogix-operator/Chart.yaml, charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml
I'm upgrading helm chart version and CRD.
=> [CHORE] upgrading helm chart

charts/coralogix-operator/Chart.yaml
This pull request bumps the version and updates the appVersion in Chart.yaml to match the tag.
=> Bump version and update appVersion in Chart.yaml

controllers/prometheusrule_controller.go, controllers/prometheusrule_controller_test.go, go.mod, go.sum
I'm refactoring the prometheus rule controller, we fixed a few bugs during reconciling because rules were not being created.
=> [CHORE] refactoring prometheus rule controller

controllers/alphacontrollers/recordingrulegroupset_controller.go, controllers/alphacontrollers/recordingrulegroupset_controller_test.go, controllers/prometheusrule_controller.go
I'm refactoring the record group rule set in order to fix some identified issues to reconcile rules and improve maintainability.
=> Refactoring record group rule set controller

controllers/prometheusrule_controller.go
Fixing: default recording rule interval
=> [FIX] default recording rule interval

apis/coralogix/v1alpha1/alert_types.go
=> [FIX] split timezone

config/rbac/role.yaml, controllers/alertmanagerconfig_controller.go, go.mod, go.sum, tests/e2e/alert_test.go, tests/e2e/alertmanager_config_test.go, tests/e2e/client.go, tests/e2e/e2e_suite_test.go, tests/e2e/outbound_webhook_test.go, tests/e2e/prometheus_rule_test.go, tests/e2e/recording_rule_group_test.go, tests/e2e/rule_group_test.go
=> Add E2E tests

internal/controller/coralogix/alert_controller.go, internal/controller/coralogix/outboundwebhook_controller.go, internal/controller/coralogix/recordingrulegroupset_controller.go, internal/controller/coralogix/rulegroup_controller.go
The issue: 
When the user creates a CR (CRD instance), the operator creates a remote resource and stores its ID in the CR status. If this status update operation fails, the ID property remains empty, and then the operator will create the same remote resource in the next reconciliation, so there is a duplicated remote resource.
The solution:
If the status update operation fails, delete the newly created remote resource. The next reconciliation will take care of recreating it.
=> Clean up after failing to store the status

cmd/main.go, internal/controller/alertmanagerconfig_controller.go, internal/controller/coralogix/alert_controller.go, internal/controller/coralogix/outboundwebhook_controller.go, internal/controller/coralogix/recordingrulegroupset_controller.go, internal/controller/coralogix/rulegroup_controller.go, internal/controller/prometheusrule_controller.go, internal/monitoring/metrics.go, internal/webhook/coralogix/v1alpha1/outboundwebhook_webhook.go, internal/webhook/coralogix/v1alpha1/rulegroup_webhook.go
Fixes #198 
Added metrics:
```
cx_operator_alert_info
cx_operator_rule_group_info
cx_operator_outbound_webhook_info
cx_operator_recording_rule_group_set_info
cx_operator_tracked_prometheus_rule_info
cx_operator_tracked_alertmanager_config_info
cx_operator_outbound_webhooks_rejected_total
cx_operator_rule_groups_rejected_total
```
=> Add metrics

config/manager/manager.yaml, internal/controller/coralogix/alert_controller.go, internal/controller/coralogix/apikey_controller.go, internal/controller/coralogix/outboundwebhook_controller.go
=> Align controllers log verbosity level

Makefile, internal/controller/coralogix/rulegroup_controller.go, internal/controller/coralogix/rulegroup_controller_test.go
Fix RuleGroup unit test which #186 broke.
=> Fix RuleGroup unit test

internal/controller/prometheusrule_controller.go
=> Fix PrometheusRule issue

README.md, internal/webhook/coralogix/v1alpha1/apikey_webhook.go, internal/webhook/coralogix/v1alpha1/rulegroup_webhook.go, tests/e2e/api_key_test.go
Fix validation webhooks issue- When there are multiple configuration issues, it doesn't show multiple errors. Also mention cert-manager installation in the readme.
=> Various fixes

charts/coralogix-operator/templates/NOTES.txt, charts/coralogix-operator/templates/deployment.yaml, charts/coralogix-operator/values.yaml, cmd/main.go, config/manager/manager.yaml, go.mod, go.sum, internal/controller/clientset/callPropertiesCreator.go
Also allow using custom domain with helm.
=> Map operator region env to SDK region

api/coralogix/v1alpha1/customrole_types.go, api/coralogix/v1alpha1/group_types.go, api/coralogix/v1alpha1/scope_types.go, charts/coralogix-operator/templates/crds/coralogix.com_customroles.yaml, charts/coralogix-operator/templates/crds/coralogix.com_groups.yaml, charts/coralogix-operator/templates/crds/coralogix.com_scopes.yaml, config/crd/bases/coralogix.com_customroles.yaml, config/crd/bases/coralogix.com_groups.yaml, config/crd/bases/coralogix.com_scopes.yaml, internal/webhook/coralogix/v1alpha1/apikey_webhook.go
=> Add MinItems kubebuilder validation

charts/coralogix-operator/README.md, charts/coralogix-operator/templates/certificate.yaml, charts/coralogix-operator/templates/issuer.yaml, charts/coralogix-operator/templates/webhook.yaml, charts/coralogix-operator/values.yaml, tests/e2e/alert_test.go, tests/e2e/connector_test.go, tests/e2e/global_router_test.go, tests/e2e/preset_test.go
Also change Preset and Connector names in e2e tests to be unique (backend requires it now).
=> Add feature flags for webhooks related resources

internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go
Frequent updates to custom resources can lead to stale cache issues, causing reconciliations to operate on outdated resource versions. This results in errors like:
`the object has been modified; please apply your changes to the latest version and try again`
Although these errors automatically trigger another reconciliation that eventually succeeds, they create unnecessary log noise, potentially misleading users into thinking there is a persistent issue.
This PR:
- Removes an unnecessary update operation that was contributing to frequent conflicts.
- Handles stale resource conflicts gracefully by requeuing without logging errors, preventing log flooding.
=> Fix object has been modified error

internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go, internal/controller/coralogix/v1alpha1/alertscheduler_controller.go, internal/controller/coralogix/v1alpha1/apikey_controller.go, internal/controller/coralogix/v1alpha1/customrole_controller.go, internal/controller/coralogix/v1alpha1/dashboard_controller.go, internal/controller/coralogix/v1alpha1/dashboardsfolder_controller.go, internal/controller/coralogix/v1alpha1/group_controller.go, internal/controller/coralogix/v1alpha1/integration_controller.go, internal/controller/coralogix/v1alpha1/outboundwebhook_controller.go, internal/controller/coralogix/v1alpha1/recordingrulegroupset_controller.go, internal/controller/coralogix/v1alpha1/rulegroup_controller.go, internal/controller/coralogix/v1alpha1/scope_controller.go, internal/controller/coralogix/v1alpha1/tcologspolicies_controller.go, internal/controller/coralogix/v1alpha1/tcotracespolicies_controller.go, internal/controller/coralogix/v1beta1/alert_controller.go, internal/utils/consts.go, tools/cxo-observer/README.md, tools/cxo-observer/collector.go, tools/cxo-observer/main.go
- Allow users to change specific resources log verbosity, by using `app.coralogix.com/log-verbosity` annotation. 
- Enhance `cxo-observer` CLI to collect operator pods logs.
=> Improve debugging backend requests experience

api/coralogix/v1beta1/alert_types.go, charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml, config/crd/bases/coralogix.com_alerts.yaml, docs/api.md
Cherry pick of https://github.com/coralogix/coralogix-operator/pull/360.
=> release-0.5: fixing metric-alert lessThan bug

.github/workflows/container.yaml
cherry-pick of https://github.com/coralogix/coralogix-operator/pull/365.
=> Release-0.5: Avoid tagging image as latest

.github/workflows/container.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/generated-files.yml, .github/workflows/helm-chart-deploy.yml, .github/workflows/helm-e2e-tests.yaml, .github/workflows/helm-sync-check.yaml, .github/workflows/helm-update.yaml, .github/workflows/integration-tests.yaml, .github/workflows/unit-tests.yaml
cherry picks of https://github.com/coralogix/coralogix-operator/pull/353 and https://github.com/coralogix/coralogix-operator/pull/365.
=> Release-0.4: Update workflows to support multiple branches

api/coralogix/v1alpha1/tcologspolicies_types.go, api/coralogix/v1beta1/alert_types.go, charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml, cmd/main.go, config/crd/bases/coralogix.com_alerts.yaml, config/samples/v1beta1/alerts/logs_ratio_threshold.yaml, config/samples/v1beta1/alerts/logs_threshold.yaml, config/samples/v1beta1/alerts/logs_time_relative_threshold.yaml, config/samples/v1beta1/alerts/metric_threshold.yaml, docs/api.md, tests/e2e/alert_test.go
cherry pick https://github.com/coralogix/coralogix-operator/pull/407.
=> [release-1.0] Alerts: Use root priority when override isn't set

docs/metrics.md, internal/monitoring/metrics.go
Added metrics:
- `cx_operator_client_requests_total`
- `cx_operator_client_requests_latency_seconds`
=> Add total requests and latency metrics
