coralogix/coralogix-operator

- controllers/prometheusrule_controller.go
PrometheusRule `for` field is optional but in Coralogix it's required.
Another deference, is that in Coralogix it can be just one of - [1m, 5m, 10m, 15m, 20m, 30m, 1H, 2H, 4H, 6H, 12H, 24H].
How do we want to handle empty `for`, and how do we want to handle `for` which is not one of the options above?
> patch - adding default value for alert timeWindow from PrometheusRule

- controllers/alphacontrollers/alert_controller.go
- tests/e2e/alerts/lucene/00-assert.yaml
- tests/e2e/alerts/new-value/00-assert.yaml
- tests/e2e/alerts/promql/00-assert.yaml
- tests/e2e/alerts/ratio/00-assert.yaml
- tests/e2e/alerts/standard/00-assert.yaml
- tests/e2e/alerts/time-relative/00-assert.yaml
- tests/e2e/alerts/trace/00-assert.yaml
- tests/e2e/alerts/unique-count/00-assert.yaml
e.g. - 
```
apiVersion: coralogix.com/v1alpha1
kind: Alert
metadata:
labels:
app.kubernetes.io/name: alert
app.kubernetes.io/instance: alert-sample
app.kubernetes.io/part-of: coralogix-operator
app.kuberentes.io/managed-by: kustomize
app.kubernetes.io/created-by: coralogix-operator
name: standard-alert-example
spec:
name: standard alert example
description: alert from k8s operator
severity: Info
alertType:
standard:
filters:
searchQuery: remote_addr_enriched:/.*/
conditions:
alertWhen: More
threshold: 5
timeWindow: FiveMinutes
status:
active: true
alertType:
standard:
conditions:
alertWhen: More
threshold: 5
timeWindow: FiveMinutes
filters:
searchQuery: remote_addr_enriched:/.*/
description: alert from k8s operator
**labels:
managed-by: coralogix-operator**
name: standard alert example …
```
> patch - adding label managed-by:coralogix-operator to alerts

- controllers/alphacontrollers/alert_controller.go
I'm fixing issues we faced with nil pointer addresses.
> [FIX] nil memory pointer std alerts

- apis/coralogix/v1alpha1/alert_types.go
- apis/coralogix/v1alpha1/alert_types_test.go
It turns out that NotificationGroups and Notifications within each NotificationGroup do not maintain the creation order, therefore a different type of comparison between spec and status is needed.
> Fixing notification groups deep equal bug

- controllers/alphacontrollers/alert_controller.go
After deploying the coralogix-operator to staging and euplatform clusters, we noticed that it wold eventually get nilpointer exceptions on `apis/coralogix/v1alpha1/alert_types.go:1082`:
```
{"level":"info","ts":"2023-08-02T14:58:25Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"alert","controllerGroup":"coralogix.com","controllerKind":"Alert","Alert":{"name":"recordtoolarge-alerting-kafka-connect","namespace":"platform"},"namespace":"platform","name":"recordtoolarge-alerting-kafka-connect","reconcileID":"20721bc0-68af-4920-a506-339c860480ce"}panic: runtime error: invalid memory address or nil pointer dereference [recovered]	panic: runtime error: invalid memory address or nil pointer dereference[signal SIGSEGV: …
```
> Early error when failing to get alert status from coralogix

- .github/workflows/helm-chart-deploy.yml
- .github/workflows/helm-lint-test.yaml
- Makefile
- charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_recordingrulegroupsets.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_rulegroups.yaml
- scripts/helm-check-crd-version.sh
- scripts/helm-update-crds.sh
I'm adding a workflow to check if Helm is using the latest CRDs version
> [CHORE] updating helm crds templates

- .github/workflows/build.yml
- .github/workflows/container.yaml
- .github/workflows/docs.yml
- .github/workflows/e2e-tests.yaml
- .github/workflows/semantic-release.yml
- .github/workflows/unit-tests.yaml
I'm changing Github Actions trigger to ensure we're not running unneeded actions when we're changing only the helm chart.
> [CHORE] improving action trigger

- apis/coralogix/v1alpha1/alert_types.go
- apis/coralogix/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/coralogix.com_alerts.yaml
- controllers/alphacontrollers/alert_controller.go
- docs/api.md
Remove group-by array from promql-alert spec since when filling `group-by` through the query (e.g.
- 
```yaml
searchQuery: |-
sum(
max_over_time(aws_autoscaling_group_in_service_instances_average[15m] offset 30m) 
/ 
aws_autoscaling_group_total_instances_average offset 30m
) **by (auto_scaling_group_name, region, cluster, env)**
```
), the alerts-API returns the group-by in the designated field as well (
```yaml
groupBy: [auto_scaling_group_name, region, cluster, env]
```
), which causes a diff between the spec and the status and an attempt to update the CR forever.
> remove group-by from promql alert spec

- controllers/alphacontrollers/alert_controller.go
This pull request includes changes to the `alert_controller.go` file, specifically within the `flattenNotificationGroups` and `flattenNotifications` functions. The changes are primarily focused on error handling and flow control.
Here are the most important changes:
* `controllers/alphacontrollers/alert_controller.go`:
* In the `flattenNotificationGroups` function, the condition for the error check has been modified. Previously, it was checking a variable `err` which wasn't updated inside the loop. Now, it correctly checks `flattenErr`, which is the error returned from the `flattenNotificationGroup` function. This ensures that any errors encountered during the flattening process are properly caught and handled.
* In the `flattenNotifications` function, a `continue` statement has been …
> [FIX] error checking causing panic

- controllers/prometheusrule_controller.go
Adding WithEventFilter to allow us reduce the amount of resources we're reconciling, if the object didn't match the reconcile rule it will not be added to the work queue.
REf: https://stuartleeks.com/posts/kubebuilder-event-filters-part-1-delete/
> [REFACTOR] prometheus rules reconcile

- controllers/alphacontrollers/alert_controller.go
- controllers/alphacontrollers/alert_controller_test.go
- controllers/alphacontrollers/rulegroup_controller.go
- controllers/alphacontrollers/rulegroup_controller_test.go
- controllers/alphacontrollers/utils.go
We are removing the default enqueue on success because the controller runtime already synchronizes the watched resources every 10 hours by default. Therefore, forcing a reschedule upon successful reconciliation is unnecessary.
In the future, if needed, we can introduce a flag to adjust the sync period.
> [CHORE] removing reschedule on sucess

- controllers/prometheusrule_controller.go
Not creating recording rule set when the rules are empty
> [FIX] empty rule group

- controllers/alphacontrollers/recordingrulegroupset_controller.go
I'm adding recording rule group set name to the Coralogix API Call.
> [CHORE] adding recording rule group set

- controllers/alphacontrollers/recordingrulegroupset_controller.go
- main.go
I'm adding suffix flag to allow users add a suffix to the recording rule name, avoiding clashing names when you have same resource distributed cross cluster.
> [CHORE] adding recording rule group set suffix flag

- apis/coralogix/v1alpha1/recordingrulegroupset_types.go
- config/crd/bases/coralogix.com_recordingrulegroupsets.yaml
- controllers/prometheusrule_controller.go
- docs/api.md
Enforcing default interval is a better approach in this case than block on CRD, since some customers might have generate prometheus rules being created by third part service that don't allow rule interval configuration.
> [CHORE] enforcing default value instead of block cr onboarding

- charts/coralogix-operator/templates/_helpers.tpl
- charts/coralogix-operator/templates/deployment.yaml
If secretKeyReference is defined then use the secret key name, otherwise default to `CORALOGIX_API_KEY`
> adding coralogixOperator.secretKey function

- README.md
> README: fix installation instructions

- CONTRIBUTING.md
- charts/coralogix-operator/templates/NOTES.txt
- charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_recordingrulegroupsets.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_rulegroups.yaml
- config/crd/bases/coralogix.com_alerts.yaml
- config/crd/bases/coralogix.com_outboundwebhooks.yaml
- config/crd/bases/coralogix.com_recordingrulegroupsets.yaml
- config/crd/bases/coralogix.com_rulegroups.yaml
- config/default/manager_auth_proxy_patch.yaml
- docs/api.md
- main.go
Also ran `make generate-api-docs` and `make helm-update-crds`.
> Add official cluster shorthands to region flags

- charts/coralogix-operator/templates/clusterrole.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_outboundwebhooks.yaml
Changes:
- Added the `OutboundWebhook` crd to helm chart
- Updated the k8s clusterole permissions to support the outboundwebooks
Related Issue:
https://github.com/coralogix/coralogix-operator/issues/166
> Adding the OutboundWebhook CRD and permissions to the helm chart

- controllers/alertmanagerconfig_controller.go
- controllers/prometheusrule_controller.go
- tests/e2e/prometheus_rule_test.go
Fixes https://github.com/coralogix/coralogix-operator/issues/176
> Reconcile for owned resources

- controllers/alertmanagerconfig_controller.go
- controllers/prometheusrule_controller.go
- tests/e2e/prometheus_rule_test.go
Reverts coralogix/coralogix-operator#180 which introduced race conditions between the controllers, and this raised the following error for alerts and outboundwebhooks:
`the object has been modified; please apply your changes to the latest version and try again`.
> Revert "Reconcile for owned resources"

- internal/controller/prometheusrule_controller.go
- tests/integration/alertmangerconfigs/alertmangerconfig-basic/03-assert.yaml
- tests/integration/alertmangerconfigs/alertmangerconfig-basic/05-assert.yaml
- tests/integration/prometheusrules/prometheusrules-basic/03-install.yaml
We decided not to support configuring Coralogix Alert CRD special properties through Prometheus alerts annotations and labels. Instead we will support updating those extra properties in the alert CRD itself, without being overwritten.
Reverts coralogix/coralogix-operator#212
> Revert "Support cxMinNonNullValuesPercentage annotation from PrometheusRule"

- api/coralogix/v1alpha1/connector_types.go
- api/coralogix/v1alpha1/globalrouter_types.go
- api/coralogix/v1alpha1/preset_types.go
- charts/coralogix-operator/templates/crds/coralogix.com_connectors.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_globalrouters.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_presets.yaml
- config/crd/bases/coralogix.com_connectors.yaml
- config/crd/bases/coralogix.com_globalrouters.yaml
- config/crd/bases/coralogix.com_presets.yaml
- docs/api.md
- GlobalRouter fallback should be optional, as the API behaves.
- Add comments about the new NC CRDs to docs, mentioning they can have breaking changes in the near future.
> Change GlobalRouter fallback to optional

- .github/workflows/e2e-tests.yaml
- .github/workflows/generated-files.yml
- .github/workflows/helm-e2e-tests.yaml
- .github/workflows/integration-tests.yaml
- scripts/collect-logs.sh
- tests/e2e/custom_role_test.go
- tests/e2e/group_test.go
- tests/e2e/recording_rule_group_test.go
- tests/e2e/rule_group_test.go
- tests/e2e/tco_logs_policies_test.go
- tests/e2e/tco_traces_policies_test.go
- Use arbitrary names for resources on e2e tests, to avoid flakiness caused by conflicts.
- Remove the update check for TCO policies, as it's another atomic operation that causes flakiness.
- Upload operator pod logs after e2e and integration tests runs, to improve debugging.
- Add `go mod tidy` validation to `generate` workflow.
> Fix e2e tests flakiness and upload pod logs after tests

- api/coralogix/v1alpha1/groupversion_info.go
- api/coralogix/v1beta1/alert_types.go
- api/coralogix/v1beta1/groupversion_info.go
- cmd/main.go
- internal/controller/alertmanagerconfig_controller.go
- internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go
- internal/controller/coralogix/v1alpha1/apikey_controller.go
- internal/controller/coralogix/v1alpha1/outboundwebhook_controller.go
- internal/controller/coralogix/v1alpha1/recordingrulegroupset_controller.go
- internal/controller/coralogix/v1alpha1/rulegroup_controller.go
- internal/controller/coralogix/v1beta1/alert_controller.go
- internal/controller/prometheusrule_controller.go
- internal/controller/prometheusrule_controller_test.go
- internal/monitoring/collectors.go
- internal/monitoring/metrics.go
- internal/utils/consts.go
- internal/utils/utils.go
- internal/webhook/coralogix/v1alpha1/apikey_webhook.go
- internal/webhook/coralogix/v1alpha1/outboundwebhook_webhook.go
- internal/webhook/coralogix/v1alpha1/rulegroup_webhook.go
- internal/webhook/coralogix/v1beta1/alert_webhook.go
Added/improved metrics:
- `cx_operator_resource_info` - A gauge metric with a record per Coralogix custom resource/`PrometheusRule`/`AlertmanagerConfig` that are tracked by the operator. 
Its implementation is based on a collector that collects all k8s resources in API group `coralogix.com` (and`PrometheusRules`/`AlertmanagerConfigs`), and it is triggered when a request to the `/metrics` endpoint is made. Because it collects all Coralogix's API group resources, NO additional code is required for future Coralogix CRDs.
The status label is empty at the moment, but will be populated based on resource conditions, once they are implemented.
- `cx_operator_resource_rejections_total` - A counter metric with a record per resource, that is incremented on every coralogix-operator's validation …
> Improve metrics

- Makefile
- api/coralogix/v1alpha1/alert_conversion.go
- charts/coralogix-operator/templates/service_monitor.yaml
- charts/coralogix-operator/values.yaml
- config/default/kustomization.yaml
- config/prometheus/monitor.yaml
- docs/metrics.md
- internal/controller/prometheusrule_controller.go
- internal/monitoring/collectors.go
- Expose metrics to Prometheus using a ServiceMonitor.
- Populate `cx_operator_resource_info` metric `status` label based on resources status condition.
- Document metrics and how to send them to Coralogix.
- Add label and namespace selector to PrometheusRule controller.
- Add conditions to alert conversion.
> Monitoring enhancements

- internal/controller/prometheusrule_controller.go
- tests/e2e/prometheus_rule_test.go
In https://github.com/coralogix/coralogix-operator/pull/278, I accidentally changed the PrometheusRule controller to overwrite all the Alert Spec, which deletes its advanced fields that user may already started to use.
In this PR I fix it and add a test for it.
> fix: PrometheusRule controller to not overwrite advanced Alert fields

- internal/controller/prometheusrule_controller.go
missed on https://github.com/coralogix/coralogix-operator/pull/295.
> fix: update Alert type on PrometheusRule update

- .github/workflows/e2e-tests.yaml
- .github/workflows/helm-e2e-tests.yaml
- Makefile
- api/coralogix/v1beta1/alert_types.go
- charts/coralogix-operator/templates/cluster_role.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_connectors.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_globalrouters.yaml
- charts/coralogix-operator/templates/crds/coralogix.com_presets.yaml
- charts/coralogix-operator/templates/deployment.yaml
- charts/coralogix-operator/templates/webhook.yaml
- charts/coralogix-operator/values.yaml
- cmd/main.go
- config/manager/manager.yaml
- internal/config/config.go
- scripts/helm-sync-check.sh
Due to Notification center (NC) API instability, future breaking changes in the CRDs are expected.
This PR disables NC CRDs, controllers, webhooks and RBAC by default, allowing users to opt-in by setting: `coralogixOperator.notificationCenter.enabled=true`
> Add notification center feature flag

- charts/coralogix-operator/templates/cluster_role.yaml
`presets/status` role was accidentally left outside of the
```yaml
{{- if .Values.coralogixOperator.notificationCenter.enabled }}`
...
{{- end }}
```
which left it there even when the user doesn't enable NC (and there is no such thing as Preset on the cluster).
It had no functional impact because k8s doesn't validate that, but it can be confusing for users.
> fix presets/status role location

- internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go
- internal/utils/conditions.go
Before the common reconciler was introduced, we used to delete the remote resource if we failed to store its ID in the resource status. It was important in order to avoid creating duplicated remote resources in case the status update fails.
> Avoid duplications in case status update failed

- go.mod
- tools/cxo-observer/README.md
- tools/cxo-observer/collector.go
- tools/cxo-observer/config.go
- tools/cxo-observer/consts.go
- tools/cxo-observer/main.go
- tools/cxo-observer/selector.go
This PR adds a CLI tool named  `cxo-observer` that collects Kubernetes resources related to the Coralogix Operator installation, including both core operator components and custom resources managed by the operator.
> Add a debugging CLI tool

- api/coralogix/v1alpha1/alertscheduler_types.go
- charts/coralogix-operator/templates/crds/coralogix.com_alertschedulers.yaml
- cmd/main.go
- config/crd/bases/coralogix.com_alertschedulers.yaml
- docs/api.md
- internal/webhook/coralogix/v1alpha1/alertscheduler_webhook.go
Make `filter` and `schedule` required, as in AlertScheduler API.
> fix: AlertScheduler fields should be required

- charts/coralogix-operator/README.md
- charts/coralogix-operator/templates/deployment.yaml
- charts/coralogix-operator/values.yaml
- cmd/main.go
- docs/multi-deployment-installation.md
- internal/config/config.go
This PR does the following:
- Allow users to configure operator's deployment `replicas` from helm.
- Prevent race conditions between the deployment's replicas, by enabling leader election by default. This way, only one pod would operate and reconcile resources. 
- Change the lease name (`LeaderElectionID`) to equal the deployment name - This allows having multiple deployments in the same namespace, where each deployment's replicas have a dedicated `lease` resource.
> Improve leader election support

- charts/coralogix-operator/README.md
- cmd/main.go
- internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go
- tests/e2e/scope_test.go
When a remote resource is deleted due to unmatching selectors, remove finalizer to allow easier deletion of the k8s resource.
> fix: remove finalizer when resource doesn't match selector

- .github/workflows/e2e-tests.yaml
- .github/workflows/helm-e2e-tests.yaml
- charts/coralogix-operator/templates/deployment.yaml
- internal/config/config.go
- internal/controller/coralogix/coralogix-reconciler/coralogix_reconciler.go
- internal/controller/coralogix/v1alpha1/apikey_controller.go
- internal/utils/conditions.go
- tests/e2e/scope_test.go
Reduce number of backend updates, by:
- Limiting reconcile intervals to 30 seconds.
- Unifying `RemoteCreatedSuccessfully` and `RemoteUpdatedSuccessfully` condition to `RemoteSyncedSuccessfully`.
> Reduce number of backend updates

- charts/coralogix-operator/README.md
- charts/coralogix-operator/templates/service_monitor.yaml
- charts/coralogix-operator/values.yaml
- tests/e2e/global_router_test.go
Allow configuring the service selector namespace and its NamespaceSelector, so it can be deployed to a different namespace than the operator's.
Also, update GlobalRouter test to follow recent router deletion changes.
> Support ServiceMonitor NamespaceSelector

- api/coralogix/v1alpha1/tcologspolicies_types.go
- api/coralogix/v1beta1/alert_types.go
- charts/coralogix-operator/templates/crds/coralogix.com_alerts.yaml
- config/crd/bases/coralogix.com_alerts.yaml
- config/samples/v1beta1/alerts/logs_ratio_threshold.yaml
- config/samples/v1beta1/alerts/logs_threshold.yaml
- config/samples/v1beta1/alerts/logs_time_relative_threshold.yaml
- config/samples/v1beta1/alerts/metric_threshold.yaml
- docs/api.md
- tests/e2e/alert_test.go
Also, in TCO, log error when archive retention is not found by its name.
> Alerts: Use root priority when override isn't set

- .github/workflows/upgrade-test.yaml
Add an action that:
- Installs 2 latest minor versions, currently it's `v1.0.latest` and `v0.5.latest`.
- Upgrades to the PR from each version.
- Runs e2e tests for each upgrade.
> CI: Add upgrade lane
